env:
  PURINA_OPEN_DIR_PATH: python_modules/purina-open
  PURINA_OPEN_REPO: tacastillo/test-external
  MAIN_BRANCH_NAME: main

on:
  push:
    branches:
      - ${{ env.MAIN_BRANCH_NAME}}
    paths:
      - '${{ env.PURINA_OPEN_DIR_PATH }}/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 1
          sparse-checkout: ${{ env.PURINA_OPEN_DIR_PATH }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Trim the cone from the sparse checkout
        run: |
          mkdir -p /tmp/purina-open
          mv ${{ env.PURINA_OPEN_DIR_PATH }}/* /tmp/purina-open
          rm -rf *
          mv /tmp/purina-open/* .
          ls -R -a
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          pip install pathspec
      - name: Exclude files
        run: |
          import pathspec
          import os
          
          from pathlib import Path
          
          with open('openignore.txt', 'r') as f:
              spec = pathspec.PathSpec.from_lines('gitwildmatch', f)
          
          matches = spec.match_tree('.')
          
          for match in matches:
              print(match)
              os.remove(match)
        shell: python
      - name: debug
        run: ls -R -a
      - name: Commit files
        run: |
          rm -rf .git
          git config --global init.defaultBranch main #remove in purina


          git init
          git remote add origin https://tacastillo:${{ secrets.PAT }}@github.com/${{ env.PURINA_OPEN_REPO }}

          git fetch origin

          git reset --soft origin/main
          git config --local --add --bool push.autoSetupRemote true
          git config --local user.email "${{ github.event.head_commit.author.email }}"
          git config --local user.name "${{ github.event.head_commit.author.name }}"
          git add .
          git commit --allow-empty -m "${{ github.event.head_commit.message }}"
      - name: Push to ${{ env.PURINA_OPEN_REPO }}
        run: |
          git push -u origin HEAD --force-with-lease