name: Deploy


on:
  push:
    branches:
      - main
    paths:
      - 'python_modules/purina-open/**'
      # according to the docs, it should be able to take env vars like PURINA_OPEN_DIR_PATH, but I couldn't it get to work

env:
  PURINA_OPEN_DIR_PATH: python_modules/purina-open
  PURINA_OPEN_REPO: tacastillo/test-external
  PURINA_OPEN_BRANCH_NAME: main
  PUSHER_EMAIL: timangcas@gmail.com
  PUSHER_NAME: tacastillo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 1
          sparse-checkout: ${{ env.PURINA_OPEN_DIR_PATH }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Trim the cone from the sparse checkout
        run: |
          # Remove the top-level `.git` ref and go to the purina-open directory
          rm -rf .git
          cd ${{ env.PURINA_OPEN_DIR_PATH }}
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          pip install pathspec
      - name: Exclude files
        run: |
          import pathspec
          import os
          
          with open('openignore.txt', 'r') as f:
              spec = pathspec.PathSpec.from_lines('gitwildmatch', f)
          
          matches = spec.match_tree('.')
          
          for match in matches:
              print(match)
              os.remove(match)
        shell: python
      - name: Commit files
        run: |
          git config --global init.defaultBranch ${{ env.PURINA_OPEN_BRANCH_NAME }}

          git init
          git remote add origin https://tacastillo:${{ secrets.PAT }}@github.com/${{ env.PURINA_OPEN_REPO }}
          git fetch origin

          git reset --soft origin/${{ env.PURINA_OPEN_BRANCH_NAME }}
          git config --local user.name ${{ env.PUSHER_NAME }}
          git config --local user.email ${{ env.PUSHER_EMAIL}} 
          
          git add .
          git commit -m "Mirroring commit ${{ github.event.head_commit.id }} from internal"
      - name: Push to ${{ env.PURINA_OPEN_REPO }}
        run: |
          git push -u origin HEAD --force-with-lease
