env:
  PURINA_OPEN_DIR_PATH: /python_modules/purina-open/*
  PURINA_OPEN_REPO: tacastillo/test-external

on:
  push:
    branches:
      - main
      - master
    # paths:
    #   - ${{ env.PURINA_OPEN_DIR_PATH }}/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 1
          sparse-checkout: ${{ env.PURINA_OPEN_DIR_PATH }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: debug
        run: |
          ls -R temp
          echo "PURINA_OPEN_DIR_PATH: ${{ env.PURINA_OPEN_DIR_PATH }}"
      # - name: Set up Python 3.11
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: 3.11
      # - name: Install dependencies
      #   run: |
      #     pip install pathspec
      # - name: Exclude files
      #   run: |
      #     import pathspec
      #     import os
          
      #     from pathlib import Path
          
      #     with open('.openignore', 'r') as f:
      #         spec = pathspec.PathSpec.from_lines('gitwildmatch', f)
          
      #     matches = spec.match_tree('.')
          
      #     for match in matches:
      #         print(match)
      #         os.remove(match)
      #   shell: python
      # - name: Commit files
      #   run: |
      #     ls -a
      # # - name: Commit files
      # #   run: |
      # #     git config --local user.email "${{ github.event.head_commit.author.email }}"
      # #     git config --local user.name "${{ github.event.head_commit.author.name }}"
      # #     # git commit -m "${{ github.event.head_commit.message }}"
      # # - name: Push to ${{ env.PURINA_OPEN_REPO }}
      # #   run: |
      # #     git remote add purina_open https://tacastillo:${{ secrets.PAT }}@github.com/${{ env.PURINA_OPEN_REPO }}
      # #     git push purina_open