env:
    PURINA_OPEN_DIR_PATH: python_modules/purina-open
    PURINA_OPEN_REPO: tacastillo/test-external
  
on:
  push:
      branches:
        - main
        - master
      # paths:
      #   - ${{ env.PURINA_OPEN_DIR_PATH }}/**
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 1
          sparse-checkout: ${{ env.PURINA_OPEN_DIR_PATH }}
          token: ${{ secrets.GITHUB_TOKEN }}
      # - name: Delete ignored files
      #   run: |
      #     while read -r pattern; do
      #       find . -type f -name "$pattern" -delete
      #     done < .openignore
      # - name: Install git
      #   run: |
      #     apt update --yes
      #     apt install git --yes
      - name: Commit files
        run: |
          git config --local user.email "${{ github.event.head_commit.author.email }}"
          git config --local user.name "${{ github.event.head_commit.author.name }}"
          # git commit -m "${{ github.event.head_commit.message }}"
      # - name: Configure the origin
      #   run: |
      #     git remote add origin https://github.com/${{ env.PURINA_OPEN_REPO}}
      #     git fetch
      #     git branch --set-upstream-to=origin/main
      #     echo 'Done'
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ env.PURINA_OPEN_REPO }}
          force_with_lease: true
